Sports_Ground_Management_System/Sports_Ground_Management_System/Controllers/GroundsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sports_Ground_Management_System.Models;

namespace Sports_Ground_Management_System.Controllers
{
    [Authorize]
    public class GroundsController : Controller
    {
        private readonly MyAppDbContext _context;

        public GroundsController(MyAppDbContext context)
        {
            _context = context;
        }

        // GET: Grounds
        public async Task<IActionResult> Index()
        {
            return View(await _context.Ground.ToListAsync());
        }

        // GET: Grounds/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ground = await _context.Ground
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ground == null)
            {
                return NotFound();
            }

            return View(ground);
        }

        // GET: Grounds/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Grounds/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,Name,img,address,capacity")] Ground ground)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ground);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ground);
        }

        // GET: Grounds/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ground = await _context.Ground.FindAsync(id);
            if (ground == null)
            {
                return NotFound();
            }
            return View(ground);
        }

        // POST: Grounds/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,img,address,capacity")] Ground ground)
        {
            if (id != ground.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ground);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GroundExists(ground.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ground);
        }

        // GET: Grounds/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ground = await _context.Ground
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ground == null)
            {
                return NotFound();
            }

            return View(ground);
        }

        // POST: Grounds/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ground = await _context.Ground.FindAsync(id);
            _context.Ground.Remove(ground);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GroundExists(int id)
        {
            return _context.Ground.Any(e => e.Id == id);
        }
    }
}

Sports_Ground_Management_System/Sports_Ground_Management_System/Controllers/SlotsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ApplicationSystem.Data;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sports_Ground_Management_System.Areas.Identity.Data;
using Sports_Ground_Management_System.Models;

namespace Sports_Ground_Management_System.Controllers
{
    [Authorize]
    public class SlotsController : Controller
    {
        private readonly MyAppDbContext _context;

        public SlotsController(MyAppDbContext context)
        {
            _context = context;
        }

        // GET: Slots
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var myAppDbContext = _context.BookedSlot.Include(s => s.Ground).Include(s => s.User);
            return View(await myAppDbContext.ToListAsync());
        }

        // GET: Slots/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var slot = await _context.BookedSlot
                .Include(s => s.Ground)
                .Include(s => s.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (slot == null)
            {
                return NotFound();
            }

            return View(slot);
        }

        // GET: Slots/Create
        [Authorize(Roles = "User")]
        public IActionResult Create()
        {

            ViewData["GroundId"] = new SelectList(_context.Ground, "Id", "Name");
            ViewData["UserId"] = new SelectList(_context.Set<AspNetUsers>(), "Id", "Id");
            return View();
        }

        // POST: Slots/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User")]
        public async Task<IActionResult> Create([Bind("Id,From,To,Attendees,GroundId,UserId")] Slot slot)
        {
            if (ModelState.IsValid)
            {
                var db = new MyAppDbContext();
                List<Slot> slots = _context.BookedSlot.ToList();

                foreach(var s in slots)
                {
                    if(s.GroundId == slot.GroundId)
                    {
                        if(slot.From >= s.From && slot.From <= s.To)
                        {
                            ModelState.AddModelError(string.Empty, "Slot is not available.");
                            return Create();
                        }
                        if (slot.To >= s.From && slot.To <= s.To)
                        {
                            ModelState.AddModelError(string.Empty, "Slot is not available.");
                            return Create();
                        }
                    }
                }

                slot.UserId = User.Identity.GetUserId();
                _context.Add(slot);
                await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));
                return LocalRedirect("~/Slots/BookedSlots");
            }
            ViewData["GroundId"] = new SelectList(_context.Ground, "Id", "Name", slot.GroundId);
            //ViewData["UserId"] = new SelectList(_context.Set<AspNetUsers>(), "Id", "Id", slot.UserId);
            return View(slot);
        }

        // GET: Slots/Edit/5
        [Authorize(Roles = "User")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var slot = await _context.BookedSlot.FindAsync(id);
            if (slot == null)
            {
                return NotFound();
            }
            ViewData["GroundId"] = new SelectList(_context.Ground, "Id", "Name", slot.GroundId);
            ViewData["UserId"] = new SelectList(_context.Set<AspNetUsers>(), "Id", "Id", slot.UserId);
            return View(slot);
        }

        // POST: Slots/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,From,To,Attendees,GroundId,UserId")] Slot slot)
        {
            if (id != slot.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    slot.UserId = User.Identity.GetUserId();
                    _context.Update(slot);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SlotExists(slot.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return LocalRedirect("~/Slots/BookedSlots");
            }
            ViewData["GroundId"] = new SelectList(_context.Ground, "Id", "Name", slot.GroundId);
            ViewData["UserId"] = new SelectList(_context.Set<AspNetUsers>(), "Id", "Id", slot.UserId);
            return View(slot);
        }

        // GET: Slots/Delete/5
        [Authorize(Roles = "User")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var slot = await _context.BookedSlot
                .Include(s => s.Ground)
                .Include(s => s.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (slot == null)
            {
                return NotFound();
            }

            return View(slot);
        }

        // POST: Slots/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var slot = await _context.BookedSlot.FindAsync(id);
            _context.BookedSlot.Remove(slot);
            await _context.SaveChangesAsync();
            return LocalRedirect("~/Slots/BookedSlots");
        }

        private bool SlotExists(int id)
        {
            return _context.BookedSlot.Any(e => e.Id == id);
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> BookedSlotsAsync()
        {
            var myAppDbContext = _context.BookedSlot.Include(s => s.Ground).Include(s => s.User);
            return View(await myAppDbContext.ToListAsync());
        }
    }
}

Sports_Ground_Management_System/Sports_Ground_Management_System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sports_Ground_Management_System</title>

    @using Microsoft.AspNetCore.Identity
    @using Sports_Ground_Management_System.Areas.Identity.Data

    @inject SignInManager<ApplicationUser> SignInManager
    @inject UserManager<ApplicationUser> UserManager

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SGMS</a>
                @if (SignInManager.IsSignedIn(User)){
                    <a class="nav-link link text-white-50" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                }
                <a class="nav-link link text-white-50" asp-area="" asp-controller="Grounds" asp-action="Index">Grounds</a>
                <a class="nav-link link text-white-50" asp-area="" asp-controller="Slots" asp-action="Index">Slots</a>
                <a class="nav-link link text-white-50" asp-area="" asp-controller="Slots" asp-action="BookedSlots">My Slots</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                   @*<ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link link text-white-50" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>*@
                    @*partial layout for logged in user.*@
                    <partial name="_LoginPartial"></partial>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Sports_Ground_Management_System - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>